/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "Schemes-Primary": "#705d00",
        "Schemes-Surface Tint": "#705d00",
        "Schemes-On-Primary": "#ffffff",
        "Schemes-Primary-Container": "#ffdc51",
        "Schemes-On-Primary-Container": "#534400",
        "Schemes-Secondary": "#6e5d1c",
        "Schemes-On-Secondary": "#ffffff",
        "Schemes-Secondary-Container": "#fde696",
        "Schemes-On-Secondary-Container": "#584907",
        "Schemes-Tertiary": "#506600",
        "Schemes-On-Tertiary": "#ffffff",
        "Schemes-Tertiary-Container": "#c8ed56",
        "Schemes-On-Tertiary-Container": "#3b4c00",
        "Schemes-Error": "#ba1a1a",
        "Schemes-On-Error": "#ffffff",
        "Schemes-Error-Container": "#ffdad6",
        "Schemes-On-Error-Container": "#410002",
        "Schemes-Background": "#ffffff",
        "Schemes-On-Background": "#1f1b10",
        "Schemes-Surface": "#fff8ef",
        "Schemes-On-Surface": "#1f1b10",
        "Schemes-Surface-Variant": "#ede2c6",
        "Schemes-On-Surthemeace-Variant": "#4d4632",
        "Schemes-Outline": "#7f775f",
        "Schemes-Outline-Variant": "#d0c6ab",
        "Schemes-Shadow": "#000000",
        "Schemes-Scrim": "#000000",
        "Schemes-Inverse-Surface": "#343024",
        "Schemes-Inverse-On-Surface": "#f9f0dd",
        "Schemes-Inverse-Primary": "#e9c400",
        "Schemes-Primary Fixed": "#ffe171",
        "Schemes-On-Primary-Fixed": "#221b00",
        "Schemes-Primary-Fixed-Dim": "#e9c400",
        "Schemes-On-Primary-Fixed-Variant": "#554600",
        "Schemes-Secondary-Fixed": "#f9e292",
        "Schemes-On-Secondary-Fixed": "#221b00",
        "Schemes-Secondary-Fixed-Dim": "#dbc679",
        "Schemes-On-Secondary-Fixed-Variant": "#544603",
        "Schemes-Tertiary-Fixed": "#cbf15a",
        "Schemes-On-Tertiary-Fixed": "#161e00",
        "Schemes-Tertiary-Fixed-Dim": "#b0d440",
        "Schemes-On-Tertiary-Fixed-Variant": "#3c4d00",
        "Schemes-Surface-Dim": "#e1d9c7",
        "Schemes-Surface-Bright": "#fff8ef",
        "Schemes-Surface-Container-Lowest": "#ffffff",
        "Schemes-Surface-Container-Low": "#fcf3e0",
        "Schemes-Surface-Container": "#f6eddb",
        "Schemes-Surface-Container-High": "#f0e7d5",
        "Schemes-Surface-Container-Highest": "#eae2cf",

        "Surfaces-Surface-Tint-5%": "#705d00",
        "Surfaces-Surface-Tint-8%": "#705d00",
        "Surfaces-Surface-Tint-11%": "#705d00",
        "Surfaces-Surface-Tint-12%": "#705d00",
        "Surfaces-Surface-Tint-14%": "#705d00",

        "sys-light-debt": "#D06117",
        "sys-light-credit": "#15832D",
        "sys-light-on-surface": "#1F1B10",
      },

      fontFamily: {
        Mono: ["Space Mono"],
        Grotesk: ["Space Grotesk"],
      },
    },
  },
  plugins: [],
};
